server:
    port: 1003

spring:
    main:
        web-application-type: servlet
    
    profiles:
        default: local
    
    application:
        name: chat_service

    config:
        import:
            - security/application-db.yml
            - security/application-api.yml
            - security/application-jwt.yml
            - security/application-oauth2.yml
