name: Chat Service CI

on:
  pull_request:
    branches:
      - develop
      - main

  push:
    branches:
      - 'feature/**'

permissions:
  contents: read
  checks: write
  pull-requests: write

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: 저장소 코드 가져오기 (Checkout)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: JDK 21 설치
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Gradle 캐시 설정
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('chat-service/**/*.gradle*', 'chat-service/**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: gradlew 실행 권한 부여
        working-directory: chat-service
        run: chmod +x ./gradlew

      - name: Gradle로 테스트 실행
        working-directory: chat-service
        run: ./gradlew --info test

      - name: 테스트 결과 리포트
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: always()
        with:
          files: 'chat-service/build/test-results/test/TEST-*.xml'
      
      - name: 테스트 결과 게시
        uses: mikepenz/action-junit-report@v4
        if: always()
        with:
          report_paths: 'chat-service/build/test-results/test/TEST-*.xml'
